### ISSUE TITLE
*DISEASE* Stroke

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/opensafely-codelist-development#20]
This follows on from #5 and [another stroke issue](https://github.com/ebmdatalab/tpp-sql-notebook/issues/63) to define "stroke" exclusively. In this issue we will
a) define in  "human" what we mean by stroke based on long overlapping discussions in 5 
b) define the codelist for https://codelists.opensafely.org/

**Comment by brianmackenna** [comment]
a) We want to identify people who have had a stroke. Only definitive diagnoses codes will be included.  Uncertain diagnosis, related codes and diagnoses that are not indicative of a stroke will be excluded in e.g. TIA,  vascular dementia, subdural bleeds, pituitary haemhorrhage.

**Comment by brianmackenna** [comment]
The new list has been further reviewed by and [is available here with comments](https://docs.google.com/spreadsheets/d/1oANnfELBiDVRoAN9GGT1jcCeLHyxEl4h-QqiYsaLZgM/edit#gid=0).

This is now on [OpenCodelists for checking](https://codelists.opensafely.org/codelist/opensafely/stroke-updated/)

NB Once checked we will have to retire other lists or rename current one to highlight change.

**Comment by laurietomlinson** [comment]
I approve this codelist @laurietomlinson

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/stroke-updated/#full-list
