### ISSUE TITLE
ICD10: COVID Identification

### ISSUE THREAD

**Issue by brianmackenna** [ebmdatalab/opensafely-codelist-development#21]
We need a list for  https://codelists.opensafely.org/

Currently defined in our study_definition as 
`covid_codelist = codelist(["U071", "U072"], system="icd10")`

The [WHO ICD-10 browser](https://icd.who.int/browse10/2019/en#/U07.1) lists the following 

U07.1
Use this code when COVID-19 has been confirmed by laboratory testing irrespective of severity of clinical signs or symptoms. Use additional code, if desired, to identify pneumonia or other manifestations.

U07.2
COVID-19, virus not identified
Use this code when COVID-19 is diagnosed clinically or epidemiologically but laboratory testing is inconclusive or not available. Use additional code, if desired, to identify pneumonia or other manifestations

Does everyone agree with this?

**Comment by alexwalkercebm** [comment]
Yes this looks correct to me.

**Comment by DarthCTR** [comment]
Yes, these are the two ICD-10s related to Covid-19. Can I suggest flagging them differently though? Have we used terminology like "confirmed" and "suspected" in other variables? U07.1 is more in line with confirmed. And U07.2 suspected.

**Comment by brianmackenna** [comment]
We can certainly keep them separate.  For the purposes of this study we need a combined one like risk factors so I'll set this up and when we have a study requiring "suspected" we'll do the new list. I imagine for that we'll also need to consider all the [snomed "suspected covid terms](https://termbrowser.nhs.uk/?perspective=full&conceptId1=1240751000000100&edition=uk-edition&release=v20200513&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104).

**Comment by brianmackenna** [comment]
http://codelists.opensafely.org/codelist/opensafely/covid-identification/

@DarthCTR is this issue ok to be closed? And a separate one opened for different studdies definition of "covid".

**Comment by DarthCTR** [comment]
Yes. I've been convinced both codes should be used in primary analyses to identify Covid-19 death. We can run sensitivity analyses for U07.1 only depending on study/study population, so as long as we have a flag that allows us to do that, all good! Thanks!
